package com.company;

import java.util.ArrayList;

 interface AbstractCharacter {
    void setStrength(long strength);
    void setIntelligence(long intelligence);
    void setDefense(long defense);
    void setVitality(long vitality);
    void setWisdom(long wisdom);
    void setHealth(long health);
    void setMana(long mana);
    void setXp(long xp);
    void setLevel(long level);
    void setRace(String race);
    void setName(String name);
    void setClassification(String classification);
    void setInventory(ArrayList<String> inventory);
    void setXpToNextLvl(long xpToNextLvl);
    void setFirstWoodenSwordAdded(boolean firstWoodenSwordAdded);
    void setFirstBronzeSwordAdded(boolean firstBronzeSwordAdded);
    void setFirstIronSwordAdded(boolean firstIronSwordAdded);
    void setFirstGoldSwordAdded(boolean firstGoldSwordAdded);
    void setFirstLegendarySwordAdded(boolean firstLegendarySwordAdded);
    void setFirstWoodenBowAdded(boolean firstWoodenBowAdded);
    void setFirstBronzeBowAdded(boolean firstBronzeBowAdded);
    void setFirstIronBowAdded(boolean firstIronBowAdded);
    void setFirstGoldBowAdded(boolean firstGoldBowAdded);
    void setFirstLegendaryBowAdded(boolean firstLegendaryBowAdded);
    void setFirstWoodenWandAdded(boolean firstWoodenWandAdded);
    void setFirstBronzeWandAdded(boolean firstBronzeWandAdded);
    void setFirstIronWandAdded(boolean firstIronWandAdded);
    void setFirstGoldWandAdded(boolean firstGoldWandAdded);
    void setFirstLegendaryWandAdded(boolean firstLegendaryWandAdded);
    void setFirstWoodenShieldAdded(boolean firstWoodenShieldAdded);
    void setFirstBronzeShieldAdded(boolean firstBronzeShieldAdded);
    void setFirstIronShieldAdded(boolean firstIronShieldAdded);
    void setFirstGoldShieldAdded(boolean firstGoldShieldAdded);
    void setFirstLegendaryShieldAdded(boolean firstLegendaryShieldAdded);
    void setWoodenSwordStrength(long woodenSwordStrength);
    void setBronzeSwordStrength(long bronzeSwordStrength);
    void setIronSwordStrength(long ironSwordStrength);
    void setGoldSwordStrength(long goldSwordStrength);
    void setLegendarySwordStrength(long legendarySwordStrength);
    void setWoodenBowStrength(long woodenBowStrength);
    void setBronzeBowStrength(long bronzeBowStrength);
    void setIronBowStrength(long ironBowStrength);
    void setGoldBowStrength(long goldBowStrength);
    void setLegendaryBowStrength(long legendaryBowStrength);
    void setWoodenWandIntelligence(long woodenWandIntelligence);
    void setBronzeWandIntelligence(long bronzeWandIntelligence);
    void setIronWandIntelligence(long ironWandIntelligence);
    void setGoldWandIntelligence(long goldWandIntelligence);
    void setLegendaryWandIntelligence(long legendaryWandIntelligence);
    void setWoodenShieldDefense(long woodenShieldDefense);
    void setBronzeShieldDefense(long bronzeShieldDefense);
    void setIronShieldDefense(long ironShieldDefense);
    void setGoldShieldDefense(long goldShieldDefense);
    void setLegendaryShieldDefense(long legendaryShieldDefense);

    long getStrength();
    long getIntelligence();
    long getDefense();
    long getVitality();
    long getWisdom();
    long getHealth();
    long getMana();
    long getXp();
    long getLevel();
    ArrayList<String> getInventory();
    String getRace();
    String getName();
    String getClassification();
    long getXpToNextLvl();
    boolean isFirstWoodenSwordAdded();
    boolean isFirstBronzeSwordAdded();
    boolean isFirstIronSwordAdded();
    boolean isFirstGoldSwordAdded();
    boolean isFirstLegendarySwordAdded();
    boolean isFirstWoodenBowAdded();
    boolean isFirstBronzeBowAdded();
    boolean isFirstIronBowAdded();
    boolean isFirstGoldBowAdded();
    boolean isFirstLegendaryBowAdded();
    boolean isFirstWoodenWandAdded();
    boolean isFirstBronzeWandAdded();
    boolean isFirstIronWandAdded();
    boolean isFirstGoldWandAdded();
    boolean isFirstLegendaryWandAdded();
    boolean isFirstWoodenShieldAdded();
    boolean isFirstBronzeShieldAdded();
    boolean isFirstIronShieldAdded();
    boolean isFirstGoldShieldAdded();
    boolean isFirstLegendaryShieldAdded();
    long getWoodenSwordStrength();
    long getBronzeSwordStrength();
    long getIronSwordStrength();
    long getGoldSwordStrength();
    long getLegendarySwordStrength();
    long getWoodenBowStrength();
    long getBronzeBowStrength();
    long getIronBowStrength();
    long getGoldBowStrength();
    long getLegendaryBowStrength();
    long getWoodenWandIntelligence();
    long getBronzeWandIntelligence();
    long getIronWandIntelligence();
    long getGoldWandIntelligence();
    long getLegendaryWandIntelligence();
    long getWoodenShieldDefense();
    long getBronzeShieldDefense();
    long getIronShieldDefense();
    long getGoldShieldDefense();
    long getLegendaryShieldDefense();

}
